### ISSUE TITLE
HDMI audio not working

### ISSUE THREAD

**Issue by thokis** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#43]
I have the problem that neither the OnBoard HD4000 ( standalone ) or my GTX 660 Ti gets HDMI audio proper supplied with your script. I have to use the HDMIAudio.kext Version 1.0/1.1 to get HDMI sound. Could there be a bug in your SSDT-Patches that can result in such behavior? Because with my previous attempts and an fully patched DSDT I did get HDMI audio OOB without the help of some 3th-party-kext. Im using your script now out of convenience and because it does its job very well, just except in this point. 

Edit : Im using the Z77X-UD3H with the mentioned GTX 660Ti.

**Comment by theracermaster** [comment]
Could you please try [this](https://transfer.sh/NfNIJ/efi.zip) EFI folder? Make sure to back up your current EFI system partition. This uses a stripped DSDT (based off [this](https://github.com/theracermaster/hack-acpi)) instead of SSDTs, and has additional HDMI audio injection. An IOReg dump (with the new EFI folder) would be useful.

**Comment by theracermaster** [comment]
Can you post an IOReg using HD 4000 only (preferably with the original EFI folder I posted)?

**Comment by theracermaster** [comment]
This should be fixed in v2.0.0. Reopen if it's still an issue.
