### ISSUE TITLE
A couple of observations and questions

### ISSUE THREAD

**Issue by osenvosem** [theracermaster/Gigabyte-GA-Z77X-macOS-Install#57]
**System information**
 - macOS 10.12.x
 - GA-Z77X macOS Install v2.0.6
 - GA-Z77X-UD5H
 - Intel Core i7-3770K
 - NVIDIA GeForce GTX 680
 - Clover boot log (`bdmesg > log.txt`): https://transfer.sh/gqi9C/log.txt (not sure if the log is useful, because I get it after successful bootloading)
----
- If I follow the UEFI config instructions and set internal graphics to "Enabled", the system rejects booting; it resets while booting. "Auto" and "Disabled" modes are ok though.
- a keyboard inserted to USB doesn't work on the clover boot menu screen.
----
- Should I update clover installation independently?
- Is it necessary to reboot the system with the bootable usb made with "tools/mkusb" before upgrading to a new version of GA-Z77X.sh or I can do this as usual from already booted system?
----
Thank you for your work. It is awesome.

**Comment by theracermaster** [comment]
With regards to the Internal Graphics setting, you're not the first to report that booting fails with the IGPU set to Enabled. I'm not really sure why this is the case, as I personally use it with this configuration. I'll do some more testing and see if there is anything that I need to fix.

Your keyboard issue is probably caused by UsbKbDxe (used for FV2 keyboard input). I need to do some more testing, but this issue *should* disappear if you enable UEFI fast boot (it prevents the AMI USB keyboard driver from loading). Perhaps I should use @vit9696's AmiShim by default (keeping UsbKbDxe for advanced users).

I use my own build of Clover (which has additional changes that this repo depends on), so I'd recommend sticking with the version used by the script. You can update the script without having to reinstall.

**Comment by osenvosem** [comment]
@theracermaster should I do something before upgrading the script to a new version or simply clone is and run without any preparations?

**Comment by theracermaster** [comment]
I use a modified version of F16h (latest firmware available for GA-Z77X-UD5H). As for upgrading, you should just be able to run the script with `--update` as an argument. A backup of the ESP will be made in the repo folder.

**Comment by osenvosem** [comment]
@theracermaster where can I get the BIOS?

**Comment by jabba559thqm** [comment]
Hey theracermaster I am also having issues with running my igpu and the dedicated gpu.  Z77X-UD5H with 3770K...  discrete gpu is a GTX670

**Comment by theracermaster** [comment]
@jabba559thqm, I would make a new issue for any problems you're encountering with the IGPU+dGPU setup.
